// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_VictorFrias.DAL;

#nullable disable

namespace P2_AP1_VictorFrias.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251104011820_Tercera")]
    partial class Tercera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("P2_AP1_VictorFrias.Models.Componente", b =>
                {
                    b.Property<int>("ComponenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("ComponenteId");

                    b.ToTable("Componentes");

                    b.HasData(
                        new
                        {
                            ComponenteId = 1,
                            Descripcion = "Teclado",
                            Existencia = 0,
                            Precio = 0m
                        },
                        new
                        {
                            ComponenteId = 2,
                            Descripcion = "Procesador",
                            Existencia = 0,
                            Precio = 0m
                        },
                        new
                        {
                            ComponenteId = 3,
                            Descripcion = "HDI",
                            Existencia = 0,
                            Precio = 0m
                        },
                        new
                        {
                            ComponenteId = 4,
                            Descripcion = "Cable sata",
                            Existencia = 0,
                            Precio = 0m
                        },
                        new
                        {
                            ComponenteId = 5,
                            Descripcion = "Ram",
                            Existencia = 0,
                            Precio = 0m
                        },
                        new
                        {
                            ComponenteId = 6,
                            Descripcion = "Disco duro",
                            Existencia = 0,
                            Precio = 0m
                        });
                });

            modelBuilder.Entity("P2_AP1_VictorFrias.Models.Pedidos", b =>
                {
                    b.Property<int>("PedidosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("PedidosId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("P2_AP1_VictorFrias.Models.PedidosDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponenteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidosId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponenteId");

                    b.HasIndex("PedidosId");

                    b.ToTable("PedidosDetalles");
                });

            modelBuilder.Entity("P2_AP1_VictorFrias.Models.PedidosDetalle", b =>
                {
                    b.HasOne("P2_AP1_VictorFrias.Models.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("ComponenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P2_AP1_VictorFrias.Models.Pedidos", "Pedido")
                        .WithMany("PedidosDetalles")
                        .HasForeignKey("PedidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Componente");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("P2_AP1_VictorFrias.Models.Pedidos", b =>
                {
                    b.Navigation("PedidosDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
